### ISSUE TITLE
k8s ConfigMap

### ISSUE THREAD

**Issue by changmink** [changmink/changmink.github.io#11]
# ConfigMap
설정을 컨테이너와 분리하기 위해서 사용
### 특정 값만 사용하기
```
spec:
  env:
    valueFrom:
      configMapKeyRef:
        name: [선언한 configMap 이름]
```
### 볼륨으로 사용하기
